from app import Base

from sqlalchemy import Column,JSON,BIGINT,DateTime,func,ForeignKey

#1:1 -> unique 

class Game(Base):

    __tablename__="game"

    id=Column(BIGINT,primary_key=True,autoincrement=True)
    
    # 
    player_id=Column(BIGINT,ForeignKey("player.id"),unique=True,nullable=False)

    #game JSON
    board=Column(JSON,nullable=False)

    #Auto generated By The DB
    created_at=Column(DateTime(timezone=True),server_default=func.now())
