from app import Base

from sqlalchemy import Column,String,BIGINT,DateTime,func

class Player(Base):

    __tablename__="player"

    id=Column(BIGINT,primary_key=True,autoincrement=True)
    u_name=Column(String,nullable=False,unique=True)
    nick_name=Column(String,nullable=False)
    #Auto generated By The DB
    created_at=Column(DateTime(timezone=True),server_default=func.now())
